### ISSUE TITLE
Pipeline Make Training Set

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_pipelines#7]
Create pipeline to receive a request from the user (via pzserver library), perform basic cross-matching between an informed specz catalog (pre-registered data product in pz server) and a photometric catalog (Data Release). 

Requirements: 
- [ ] prevent input wrong product type (spec-z catalog only) 
- [ ] the pipeline will be executed by an administrative user ("pz-server-app") @carlosadean  
- [ ] resulting data product file format default: same as specz catalog input 
- [ ] connect back to the corresponding method in the PZ Server lib to inform output metadata 

```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/pzserver_app/issues/271
- [ ] https://github.com/linea-it/pzserver_app/issues/272
- [ ] https://github.com/linea-it/pzserver_app/issues/273
```
